export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/11.png",
    username: "James Wilson",
  },
  {
    id: 2,
    profilePicture: "assets/person/2_2.jpg",
    username: "Dave Stevens",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpg",
    username: "Seth Robinson",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpg",
    username: "Gilbert Walker",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpg",
    username: "Brian Baker",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpg",
    username: "Ethan Holmes",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpg",
    username: "Blake Chapman",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpg",
    username: "Hunter Payne",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpg",
    username: "Martin Wilson",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpg",
    username: "Clark Wilson",
  },
];

export const Posts = [
  {
    id: "1",
    desc: "What if I lose it all ? ",
    photo: "assets/post/1.jpg",
    date: "1 hour ago",
    userId: 1,
    like: 30,
    comment: 3,
  },
  {
    id: "2",
    desc: "I'm addicted to you",
    photo: "assets/post/2.jpg",
    date: "a min ago",
    userId: 2,
    like: 17,
    comment: 20,
  },
  {
    id: "3",
    desc: "under the tree where the grass don't grow, we make a promise we ll never get old ",
    photo: "assets/post/3.jpg",
    date: "20 mins ago",
    userId: 3,
    like: 40,
    comment: 3,
  },
  {
    id: "4",
    desc: "These are the day we're waiting for",
    photo: "assets/post/4.jpg",
    date: "yesterday",
    userId: 4,
    like: 30,
    comment: 3,
  },
  {
    id: "5",
    desc: "All my life I've been waiting for someone like you ",
    photo: "assets/post/5.jpg",
    date: "20/01/2022",
    userId: 5,
    like: 10,
    comment: 2,
  },
  {
    id: "6",
    photo: "assets/post/6.jpg",
    date: "1 hour ago",
    userId: 6,
    like: 35,
    comment: 1,
  },
  {
    id: "7",
    photo: "assets/post/7.jpg",
    date: "1 hour ago",
    userId: 7,
    like: 30,
    comment: 3,
  },
  {
    id: "8",
    desc: " you said you ll folow me everywhere",
    photo: "assets/post/8.jpg",
    date: "10 mins ago",
    userId: 8,
    like: 30,
    comment: 3,
  },
  {
    id: "9",
    desc: "I gotta learn to love without you",
    photo: "assets/post/9.jpg",
    date: "1 hour ago",
    userId: 9,
    like: 35,
    comment: 7,
  },
  {
    id: "10",
    desc: "fork I'm going without you ",
    photo: "assets/post/10.jpg",
    date: "5 mins ago",
    userId: 10,
    like: 30,
    comment: 3,
  },
];
